### ISSUE TITLE
cannot be pip installed on py3.7, gcc 7.2

### ISSUE THREAD

**Issue by kootenpv** [pytoolz/cytoolz#107]
`git clone https://github.com/pytoolz/cytoolz && python setup.py install` did work though

**Comment by eriknw** [comment]
Thanks for the issue.  I'll upload a new version to PyPI this weekend that you can try.

**Comment by donglixp** [comment]
tried ```git clone https://github.com/pytoolz/cytoolz && python setup.py install```, but also doesn't work.
```
Compiling cytoolz/dicttoolz.pyx because it changed.
Compiling cytoolz/functoolz.pyx because it changed.
Compiling cytoolz/itertoolz.pyx because it changed.
Compiling cytoolz/recipes.pyx because it changed.
Compiling cytoolz/utils.pyx because it changed.
[1/5] Cythonizing cytoolz/dicttoolz.pyx
[2/5] Cythonizing cytoolz/functoolz.pyx
[3/5] Cythonizing cytoolz/itertoolz.pyx
[4/5] Cythonizing cytoolz/recipes.pyx
[5/5] Cythonizing cytoolz/utils.pyx
/afs/inf.ed.ac.uk/user/s14/s1478528/py35_virenv/lib64/python3.5/site-packages/setuptools/dist.py:351: UserWarning: Normalizing '0.8.3dev' to '0.8.3.dev0'
  normalized_version,
running install
running bdist_egg
running egg_info
creating cytoolz.egg-info
writing dependency_links to cytoolz.egg-info/dependency_links.txt
writing cytoolz.egg-info/PKG-INFO
writing top-level names to cytoolz.egg-info/top_level.txt
writing requirements to cytoolz.egg-info/requires.txt
writing manifest file 'cytoolz.egg-info/SOURCES.txt'
reading manifest file 'cytoolz.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cytoolz.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-3.5
creating build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/compatibility.py -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/_signatures.py -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/utils_test.py -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/__init__.py -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/_version.py -> build/lib.linux-x86_64-3.5/cytoolz
creating build/lib.linux-x86_64-3.5/cytoolz/curried
copying cytoolz/curried/operator.py -> build/lib.linux-x86_64-3.5/cytoolz/curried
copying cytoolz/curried/__init__.py -> build/lib.linux-x86_64-3.5/cytoolz/curried
copying cytoolz/curried/exceptions.py -> build/lib.linux-x86_64-3.5/cytoolz/curried
copying cytoolz/functoolz.pyx -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/recipes.pyx -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/itertoolz.pyx -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/utils.pyx -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/dicttoolz.pyx -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/functoolz.pxd -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/dicttoolz.pxd -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/recipes.pxd -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/__init__.pxd -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/cpython.pxd -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/utils.pxd -> build/lib.linux-x86_64-3.5/cytoolz
copying cytoolz/itertoolz.pxd -> build/lib.linux-x86_64-3.5/cytoolz
creating build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_recipes.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_doctests.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_none_safe.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_functoolz.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_compatibility.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_utils.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_serialization.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_tlz.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_signatures.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_curried.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
running build_ext
building 'cytoolz.dicttoolz' extension
creating build/temp.linux-x86_64-3.5
creating build/temp.linux-x86_64-3.5/cytoolz
/opt/rh/devtoolset-6/root/usr/bin/gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -I/opt/rh/rh-python35/root/usr/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/afs/inf.ed.ac.uk/user/s14/s1478528/py35_virenv/include -I/opt/rh/rh-python35/root/usr/include/python3.5m -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-3.5/cytoolz/dicttoolz.o
gcc -pthread -shared -L/opt/rh/rh-python35/root/usr/lib64-Wl,-z,relro build/temp.linux-x86_64-3.5/cytoolz/dicttoolz.o -L/opt/rh/rh-python35/root/usr/lib64 -lpython3.5m -o build/lib.linux-x86_64-3.5/cytoolz/dicttoolz.cpython-35m-x86_64-linux-gnu.so
/usr/bin/ld: build/temp.linux-x86_64-3.5/cytoolz/dicttoolz.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
```

**Comment by eriknw** [comment]
I have been unable to reproduce this so far and don't know what the error message above means.  I can continue to try.

I added "3.7-dev" version of Python to Travis-CI test matrix (see https://travis-ci.org/eriknw/cytoolz/jobs/317422832), and it passed.

So, are you still having an issue, and is it possible to recreate the issue in a CI system?

**Comment by donglixp** [comment]
More detailed exception information:

```
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/compatibility.py -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/utils_test.py -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/_signatures.py -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/__init__.py -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/_version.py -> build/lib.linux-x86_64-3.5/cytoolz
    creating build/lib.linux-x86_64-3.5/cytoolz/curried
    copying cytoolz/curried/__init__.py -> build/lib.linux-x86_64-3.5/cytoolz/curried
    copying cytoolz/curried/exceptions.py -> build/lib.linux-x86_64-3.5/cytoolz/curried
    copying cytoolz/curried/operator.py -> build/lib.linux-x86_64-3.5/cytoolz/curried
    copying cytoolz/functoolz.pyx -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/dicttoolz.pyx -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/utils.pyx -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/recipes.pyx -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/itertoolz.pyx -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/recipes.pxd -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/cpython.pxd -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/__init__.pxd -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/itertoolz.pxd -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/utils.pxd -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/dicttoolz.pxd -> build/lib.linux-x86_64-3.5/cytoolz
    copying cytoolz/functoolz.pxd -> build/lib.linux-x86_64-3.5/cytoolz
    creating build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_dev_skip_test.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_compatibility.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_embedded_sigs.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_functoolz.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/dev_skip_test.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_serialization.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_curried.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_none_safe.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_tlz.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_itertoolz.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_recipes.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_docstrings.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_signatures.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_dicttoolz.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_doctests.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_inspect_args.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_curried_toolzlike.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    copying cytoolz/tests/test_utils.py -> build/lib.linux-x86_64-3.5/cytoolz/tests
    running build_ext
    building 'cytoolz.dicttoolz' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/cytoolz
    /opt/rh/devtoolset-6/root/usr/bin/gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -I/opt/rh/rh-python35/root/usr/include -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/disk/scratch_ssd/lidong/ner/py/include -I/opt/rh/rh-python35/root/usr/include/python3.5m -c cytoolz/dicttoolz.c -o build/temp.linux-x86_64-3.5/cytoolz/dicttoolz.o
    gcc -pthread -shared -L/opt/rh/rh-python35/root/usr/lib64-Wl,-z,relro build/temp.linux-x86_64-3.5/cytoolz/dicttoolz.o -L/opt/rh/rh-python35/root/usr/lib64 -lpython3.5m -o build/lib.linux-x86_64-3.5/cytoolz/dicttoolz.cpython-35m-x86_64-linux-gnu.so
    /usr/bin/ld: build/temp.linux-x86_64-3.5/cytoolz/dicttoolz.o: unrecognized relocation (0x2a) in section `.text'
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
    error: command 'gcc' failed with exit status 1
error
Cleaning up...
  Removing source in /tmp/pip-build-p_l9_brw/cytoolz
Command "/disk/scratch_ssd/lidong/ner/py/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p_l9_brw/cytoolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xe45ku68-record/install-record.txt --single-version-externally-managed --compile --install-headers /disk/scratch_ssd/lidong/ner/py/include/site/python3.5/cytoolz" failed with error code 1 in /tmp/pip-build-p_l9_brw/cytoolz/
Exception information:
Traceback (most recent call last):
  File "/disk/scratch_ssd/lidong/ner/py/lib64/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/disk/scratch_ssd/lidong/ner/py/lib64/python3.5/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/disk/scratch_ssd/lidong/ner/py/lib64/python3.5/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/disk/scratch_ssd/lidong/ner/py/lib64/python3.5/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/disk/scratch_ssd/lidong/ner/py/lib64/python3.5/site-packages/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/disk/scratch_ssd/lidong/ner/py/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-p_l9_brw/cytoolz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-xe45ku68-record/install-record.txt --single-version-externally-managed --compile --install-headers /disk/scratch_ssd/lidong/ner/py/include/site/python3.5/cytoolz" failed with error code 1 in /tmp/pip-build-p_l9_brw/cytoolz/
```

**Comment by eriknw** [comment]
We now build wheels for `cytoolz`, which hopefully fixes this issue. Can you try using version 0.12.0?

**Comment by jrbourbeau** [comment]
Closing this issue as resolves by shipping wheels. Please chime in if this is still an issue.
