### ISSUE TITLE
cytoolz not working in pypy

### ISSUE THREAD

**Issue by mosynaq** [pytoolz/cytoolz#118]
I just installed cytoolz on pypy 2.7.13 and ran the following:
```bash
$ pypy
>>>> import cytoolz
```
and I got:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named cytools
>>>> import cytoolz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/pypy2.7/dist-packages/cytoolz/__init__.py", line 1, in <module>
    from .itertoolz import *
ImportError: unable to load extension module '/usr/local/lib/pypy2.7/dist-packages/cytoolz/itertoolz.pypy-41-x86_64-linux-gnu.so': /usr/local/lib/pypy2.7/dist-packages/cytoolz/itertoolz.pypy-41-x86_64-linux-gnu.so: undefined symbol: PyPyString_Check
```

**Comment by mrocklin** [comment]
Cytoolz is written in Cython which was designed for CPython, not PyPy.  You probably want to use the normal `toolz` library.
