### ISSUE TITLE
Can't  install with pip install (python 3.6.4) on windows

### ISSUE THREAD

**Issue by kolobok55** [pytoolz/cytoolz#119]
Microsoft Windows [Version 10.0.16299.192]
(c) Корпорация Майкрософт (Microsoft Corporation), 2017. Все права защищены.

C:\WINDOWS\system32>pip install cytoolz
Collecting cytoolz
  Using cached cytoolz-0.9.0.tar.gz
Requirement already satisfied: toolz>=0.8.0 in c:\python36\lib\site-packages (from cytoolz)
Installing collected packages: cytoolz
  Running setup.py install for cytoolz ... error
Exception:
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 3: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 3: invalid continuation byte

C:\WINDOWS\system32>

Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by Elfoniok** [comment]
Same here, and cytoolz was installed from within venv.

**Comment by Elfoniok** [comment]
3.6.3. also not working

**Comment by eriknw** [comment]
Any luck or suggestions?  I suppose I need to set up a Windows environment for me to test on.

**Comment by eriknw** [comment]
We now build wheels for `cytoolz`, which hopefully fixes this issue. Can you try using version 0.12.0?
