### ISSUE TITLE
undefined symbol: PyFPE_jbuf on stock Ubuntu 17.10

### ISSUE THREAD

**Issue by carver** [pytoolz/cytoolz#120]
Trying to import after a successful install gives:

```sh
    from cytoolz import (
  File "~/venv/lib/python3.6/site-packages/cytoolz/__init__.py", line 3, in <module>
    from .functoolz import *
ImportError:~/venv/lib/python3.6/site-packages/cytoolz/functoolz.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
```

It appears that cytoolz was built against a cpython with `--with-fpectl` on, which causes the above error when run on a cpython that is built without the flag. Ubuntu had the flag in the stock python in 17.04, then removed the flag in 17.10

Here is the unresolved issue with Python devs discussing how to handle it: https://bugs.python.org/issue29137

Is it possible to release a cytoolz that is built against a cpython without the flag? I don't see the fpectl module imported in pytoolz. (I'm pretty clueless in the area, so pardon my ignorance).

Some other relevant discussions, which mostly suggest building your own cpython (or cytoolz) locally as the only known workaround:
- https://stackoverflow.com/a/47703373/8412986
- https://github.com/numpy/numpy/issues/8415
- https://github.com/ethereum/web3.py/issues/554

**Comment by themusicgod1** [comment]
Where did you get your cytoolz build from?

**Comment by carver** [comment]
> Where did you get your cytoolz build from?

A pip install into a fresh virtual environment in py3.6 on Ubuntu 17.10

> Am I reading this right that if it was actually packaged here, fpectl would be included?

I *think* cytoolz (as released on pypi) is expecting a symbol in fpectl, but isn't actually using it, so just building/releasing cytoolz against a cpython without fpectl would work.

This local workaround was successful for me:
```sh
$ cd /tmp
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ pip install cytoolz
...
(venv) $ git clone https://github.com/pytoolz/cytoolz.git
...
(venv) $ cd cytoolz
(venv) $ git checkout release
(venv) $ make
(venv) $ cp cytoolz/*.so /tmp/venv/lib/python3.6/site-packages/cytoolz/
(venv) $ python
>>> import cytoolz
>>>
```

**Comment by carver** [comment]
Ah, got it. I was thinking that pip was installing an already-built cytoolz, but in fact it is compiling the cython locally with pip.

I thought I was protecting against that with a fresh virtualenv, but that didn't help, because pip was caching the result of previous cytoolz builds. They were built during a `pip install` before I upgraded my OS. The previous OS release had a cpython `--with-fpectl`.

Knowing all that, everything worked with a fresh venv and:
```sh
pip install --no-cache-dir cytoolz
```

Time to go nuke my pip cache dir.

**Comment by Lvenkin2** [comment]
pip3 uninstall cytoolz
pip3 install --no-cache-dir cytoolz

and again 

```
(venv2) root@1:/home/ubuntu/web3.py# python3 /var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py 0xB8aAc54a27d40e5D71A43f114e3E5ad53071735d 1
Traceback (most recent call last):
  File "/var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py", line 7, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/home/ubuntu/web3.py/web3/__init__.py", line 1, in <module>
    import pkg_resources
  File "/home/ubuntu/venv2/lib/python3.6/site-packages/pkg_resources/__init__.py", line 26, in <module>
    import zipfile
  File "/usr/local/lib/python3.6/zipfile.py", line 13, in <module>
    import shutil
  File "/home/ubuntu/venv2/lib/python3.6/shutil.py", line 22, in <module>
    import bz2
  File "/usr/local/lib/python3.6/bz2.py", line 19, in <module>
    from threading import RLock
  File "/usr/local/lib/python3.6/threading.py", line 7, in <module>
    from traceback import format_exc as _format_exc
  File "/usr/local/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/home/ubuntu/venv2/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/home/ubuntu/venv2/lib/python3.6/tokenize.py", line 35, in <module>
    from token import *
  File "/var/www/ico.1ct.io/public_html/wp-content/themes/1ct/py/token.py", line 7, in <module>
    from web3.providers.eth_tester import EthereumTesterProvider
  File "/home/ubuntu/web3.py/web3/providers/__init__.py", line 1, in <module>
    from .base import (  # noqa: F401
  File "/home/ubuntu/web3.py/web3/providers/base.py", line 4, in <module>
    from eth_utils import (
  File "/home/ubuntu/venv2/lib/python3.6/site-packages/eth_utils/__init__.py", line 97, in <module>
    __version__ = pkg_resources.get_distribution("eth-utils").version
AttributeError: module 'pkg_resources' has no attribute 'get_distribution'
```
