### ISSUE TITLE
WIN10 Ubuntu shell: No .so files compiled on package install, resulting in "ModuleNotFoundError"

### ISSUE THREAD

**Issue by PenkoMlakar** [pytoolz/cytoolz#156]
Hi,

I am working in Ubuntu shell within WIN10 and I am trying to use cytoolz (I am using python 3.8).

The issue is, that no matter how I try to install cytoolz ("pip3 install cytoolz", downloading the source and running "setup.py install", trying different versions...) the cytoolz (sub)modules are not found, e.g. in terminal:

`
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cytoolz
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/cytoolz/__init__.py", line 1, in <module>
    from .itertoolz import *
ModuleNotFoundError: No module named 'cytoolz.itertoolz'
>>>
`

Compared to my "pure" Ubuntu 20.04 system on my other machine where I use cytoolz as well, the supposedly compiled **.so files** are not present in the dist-packages/cytoolz directory after the installation but I am not getting any errors during installation whatsoever.

And idea how to solve that issue? 

Two remarks: I did have to use "sudo" command when installing otherwise the installation fails due to not having permissions to some /temp/ folders, and I have cython, python-dev, build-essentials installed.

Kind regards

**Comment by PenkoMlakar** [comment]
I figured out that I've been using WSL version 1. So:

1.) I've removed my current Ubuntu environment on Windows 10
2.) Set WSL version 2 (for instructions see 
 https://maurogiusti.medium.com/running-ubuntu-on-windows-10-with-wsl2-c4f06b3c353
https://docs.microsoft.com/en-gb/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
3.) Installed Ubuntu again (from windows store)

Now it works fine.
