### ISSUE TITLE
Error when trying to install cytoolz

### ISSUE THREAD

**Issue by Darky2020** [pytoolz/cytoolz#197]
I am using python3.9.2 on a MacBook Air M1. I tried to install cytoolz using `pip3 install cytoolz`. It tries to install 0.12.1 but the error persists with 0.12.0 and earlier versions.

About a year ago I wrote a project on the same machine with the same python version and dependencies and it worked well. Now I try to clone the project and install the dependencies and it fails.

The resulting error log:
```
Collecting cytoolz
  Using cached cytoolz-0.12.1.tar.gz (503 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/username/Desktop/project-name/venv/bin/python3 /Users/username/Desktop/project-name/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/tmpyc5d4_3g
       cwd: /private/var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/pip-install-vvehictp/cytoolz
  Complete output (81 lines):

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      cdef readonly object func
      cdef readonly tuple args
      cdef readonly dict keywords
      cdef public object __doc__
      cdef public object __name__
      cdef public object __module__
                         ^
  ------------------------------------------------------------

  cytoolz/functoolz.pxd:18:23: '__module__' redeclared

  Error compiling Cython file:
  ------------------------------------------------------------
  ...
      cdef readonly object func
      cdef readonly tuple args
      cdef readonly dict keywords
      cdef public object __doc__
      cdef public object __name__
      cdef public object __module__
           ^
  ------------------------------------------------------------

  cytoolz/functoolz.pxd:18:9: Compiler crash in AnalyseDeclarationsTransform

  File 'ModuleNode.py', line 203, in analyse_declarations: ModuleNode(functoolz.pxd:1:0,
      full_module_name = 'cytoolz.functoolz',
      is_pxd = True)
  File 'Nodes.py', line 393, in analyse_declarations: StatListNode(functoolz.pxd:1:0)
  File 'Nodes.py', line 5449, in analyse_declarations: CClassDefNode(functoolz.pxd:10:5,
      as_name = 'curry',
      class_name = 'curry',
      in_pxd = True,
      module_name = '',
      punycode_class_name = 'curry',
      visibility = 'private')
  File 'Nodes.py', line 393, in analyse_declarations: StatListNode(functoolz.pxd:11:4)
  File 'Nodes.py', line 1529, in analyse_declarations: CVarDefNode(functoolz.pxd:18:9,
      in_pxd = True,
      modifiers = [...]/0,
      visibility = 'public')

  Compiler crash traceback from this point on:
    File "/private/var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/pip-build-env-4goi43h8/overlay/lib/python3.9/site-packages/Cython/Compiler/Nodes.py", line 1529, in analyse_declarations
      self.entry = dest_scope.declare_var(
    File "/private/var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/pip-build-env-4goi43h8/overlay/lib/python3.9/site-packages/Cython/Compiler/Symtab.py", line 2388, in declare_var
      entry = self.declare(name, cname, type, pos, visibility)
    File "/private/var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/pip-build-env-4goi43h8/overlay/lib/python3.9/site-packages/Cython/Compiler/Symtab.py", line 550, in declare
      entries[name].already_declared_here()
    File "/private/var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/pip-build-env-4goi43h8/overlay/lib/python3.9/site-packages/Cython/Compiler/Symtab.py", line 262, in already_declared_here
      error(self.pos, "Previous declaration is here")
    File "/private/var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/pip-build-env-4goi43h8/overlay/lib/python3.9/site-packages/Cython/Compiler/Errors.py", line 178, in error
      raise InternalError(message)
  InternalError: Internal compiler error: Previous declaration is here
  [1/5] Cythonizing cytoolz/dicttoolz.pyx
  [2/5] Cythonizing cytoolz/functoolz.pyx
  Traceback (most recent call last):
    File "/Users/username/Desktop/project-name/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/username/Desktop/project-name/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/username/Desktop/project-name/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/pip-build-env-4goi43h8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/private/var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/pip-build-env-4goi43h8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/pip-build-env-4goi43h8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/pip-build-env-4goi43h8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 85, in <module>
    File "/private/var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/pip-build-env-4goi43h8/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
      cythonize_one(*args)
    File "/private/var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/pip-build-env-4goi43h8/overlay/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
      raise CompileError(None, pyx_file)
  Cython.Compiler.Errors.CompileError: cytoolz/functoolz.pyx
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/username/Desktop/project-name/venv/bin/python3 /Users/username/Desktop/project-name/venv/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/l8/88fmz0254kx7_4vn57wmxgtr0000gn/T/tmpyc5d4_3g Check the logs for full command output.
```

**Comment by romanovj** [comment]
try

echo "cython<3.0" >> c.txt
PIP_CONSTRAINT=c.txt pip install cytoolz

**Comment by Darky2020** [comment]
This worked, thanks
