### ISSUE TITLE
Cannot build cytoolz wheel

### ISSUE THREAD

**Issue by liam-ot** [pytoolz/cytoolz#202]
python version: 3.11.3
cytoolz version: 0.12.0

attempting to install eth-brownie 1.19.3 (also occurs with 1.19.1, and 1.19.2) results in this error:
```
Collecting eth-brownie
  Using cached eth_brownie-1.19.3-py3-none-any.whl (232 kB)
Collecting aiohttp==3.8.3
  Using cached aiohttp-3.8.3-cp311-cp311-macosx_10_9_x86_64.whl (355 kB)
Collecting aiosignal==1.2.0
  Using cached aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting asttokens==2.0.5
  Using cached asttokens-2.0.5-py2.py3-none-any.whl (20 kB)
Collecting async-timeout==4.0.2
  Using cached async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting attrs==22.1.0
  Using cached attrs-22.1.0-py2.py3-none-any.whl (58 kB)
Collecting base58==2.1.1
  Using cached base58-2.1.1-py3-none-any.whl (5.6 kB)
Collecting bitarray==2.6.0
  Using cached bitarray-2.6.0.tar.gz (102 kB)
  Preparing metadata (setup.py) ... done
Collecting black==22.10.0
  Using cached black-22.10.0-1fixedarch-cp311-cp311-macosx_11_0_x86_64.whl (1.4 MB)
Collecting certifi==2022.9.24
  Using cached certifi-2022.9.24-py3-none-any.whl (161 kB)
Collecting charset-normalizer==2.1.1
  Using cached charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting click==8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting cytoolz==0.12.0
  Using cached cytoolz-0.12.0.tar.gz (502 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [86 lines of output]
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef readonly object func
          cdef readonly tuple args
          cdef readonly dict keywords
          cdef public object __doc__
          cdef public object __name__
          cdef public object __module__
                             ^
      ------------------------------------------------------------
      
      cytoolz/functoolz.pxd:18:23: '__module__' redeclared
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          cdef readonly object func
          cdef readonly tuple args
          cdef readonly dict keywords
          cdef public object __doc__
          cdef public object __name__
          cdef public object __module__
               ^
      ------------------------------------------------------------
      
      cytoolz/functoolz.pxd:18:9: Compiler crash in AnalyseDeclarationsTransform
      
      File 'ModuleNode.py', line 203, in analyse_declarations: ModuleNode(functoolz.pxd:1:0,
          full_module_name = 'cytoolz.functoolz',
          is_pxd = True)
      File 'Nodes.py', line 393, in analyse_declarations: StatListNode(functoolz.pxd:1:0)
      File 'Nodes.py', line 5449, in analyse_declarations: CClassDefNode(functoolz.pxd:10:5,
          as_name = 'curry',
          class_name = 'curry',
          in_pxd = True,
          module_name = '',
          punycode_class_name = 'curry',
          visibility = 'private')
      File 'Nodes.py', line 393, in analyse_declarations: StatListNode(functoolz.pxd:11:4)
      File 'Nodes.py', line 1529, in analyse_declarations: CVarDefNode(functoolz.pxd:18:9,
          in_pxd = True,
          modifiers = [...]/0,
          visibility = 'public')
      
      Compiler crash traceback from this point on:
        File "/private/var/folders/ds/3tv3twjd03l7hm1_44d5ll3m0000gn/T/pip-build-env-_2lszbcm/overlay/lib/python3.11/site-packages/Cython/Compiler/Nodes.py", line 1529, in analyse_declarations
          self.entry = dest_scope.declare_var(
                       ^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ds/3tv3twjd03l7hm1_44d5ll3m0000gn/T/pip-build-env-_2lszbcm/overlay/lib/python3.11/site-packages/Cython/Compiler/Symtab.py", line 2388, in declare_var
          entry = self.declare(name, cname, type, pos, visibility)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ds/3tv3twjd03l7hm1_44d5ll3m0000gn/T/pip-build-env-_2lszbcm/overlay/lib/python3.11/site-packages/Cython/Compiler/Symtab.py", line 550, in declare
          entries[name].already_declared_here()
        File "/private/var/folders/ds/3tv3twjd03l7hm1_44d5ll3m0000gn/T/pip-build-env-_2lszbcm/overlay/lib/python3.11/site-packages/Cython/Compiler/Symtab.py", line 262, in already_declared_here
          error(self.pos, "Previous declaration is here")
        File "/private/var/folders/ds/3tv3twjd03l7hm1_44d5ll3m0000gn/T/pip-build-env-_2lszbcm/overlay/lib/python3.11/site-packages/Cython/Compiler/Errors.py", line 178, in error
          raise InternalError(message)
      InternalError: Internal compiler error: Previous declaration is here
      [1/5] Cythonizing cytoolz/dicttoolz.pyx
      [2/5] Cythonizing cytoolz/functoolz.pyx
      Traceback (most recent call last):
        File "/redacted/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/redacted/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/redacted/venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ds/3tv3twjd03l7hm1_44d5ll3m0000gn/T/pip-build-env-_2lszbcm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/ds/3tv3twjd03l7hm1_44d5ll3m0000gn/T/pip-build-env-_2lszbcm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/ds/3tv3twjd03l7hm1_44d5ll3m0000gn/T/pip-build-env-_2lszbcm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/ds/3tv3twjd03l7hm1_44d5ll3m0000gn/T/pip-build-env-_2lszbcm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 85, in <module>
        File "/private/var/folders/ds/3tv3twjd03l7hm1_44d5ll3m0000gn/T/pip-build-env-_2lszbcm/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1134, in cythonize
          cythonize_one(*args)
        File "/private/var/folders/ds/3tv3twjd03l7hm1_44d5ll3m0000gn/T/pip-build-env-_2lszbcm/overlay/lib/python3.11/site-packages/Cython/Build/Dependencies.py", line 1301, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: cytoolz/functoolz.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip
```

this is making it not possible to install eth-brownie and work on my vyper project, can you please help?

By the way, thanks for maintaining this repo! @eriknw  and crew

**Comment by eriknw** [comment]
Hi @liam-ot, thanks for the kind words and asking for help.

You have two options:
1. Use Cython < 3
2. Use `cytoolz` >= 0.12.2

The error you showed is due to changes from Cython 3, and these have been fixed with the latest version of `cytoolz`.

**Comment by liam-ot** [comment]
Unfortunately I am not in control of the package versions, the issue is arising from trying to use the eth-brownie package which at the moment requires a `cytoolz` v0.12.0

i've seen others comment saying downgrading to python 3.9 is a workaround so im going to attempt that for time time being and also open an issue in eth-brownie about upgrading their `cytoolz` package version

This one seems to be out of your control in this case so I think its safe for you to close the issue, thanks for the quick response @eriknw

**Comment by BobaFett-PyJs** [comment]
Hi, it is currently the end of September and I am experiencing the same error with Cytoolz 0.12.2 being incompatible with the Ethereum-brownie installer trying to build package 'cytoolz 0.12.0'

I was wondering if you have found a solution for this.

**Comment by liam-ot** [comment]
@BobaFett-PyJs eth-brownie is no longer supported, you should migrate to a new platform. I suggest [ApeWorx](https://github.com/ApeWorX/ape) as it is the de facto successor to eth-brownie and has a very simple migration guide for existing eth-brownie projects

btw @eriknw im gonna close this as you have mentioned a solution above
