### ISSUE TITLE
Tests fail with Python 3.5

### ISSUE THREAD

**Issue by FRidh** [pytoolz/cytoolz#73]
Several tests fail with Python 3.5. I also noticed 3.5 is not tested by Travis.
```
======================================================================
ERROR: test_docstrings.test_get_in_doctest
----------------------------------------------------------------------
KeyError: 'y'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/nk6l3r684z1fh6pzrbm6xrzkcz9knj57-python3.5-nose-1.3.7/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/nix/store/fgcf8i2dq5jn5bm0abpsxjccmbzdcak2-python3.5-cytoolz-0.7.4/lib/python3.5/site-packages/cytoolz/tests/test_docstrings.py", line 85, in test_get_in_doctest
    raises(KeyError, lambda: cytoolz.get_in(['y'], {}, no_default=True))
  File "cytoolz/utils.pyx", line 13, in cytoolz.utils.raises (cytoolz/utils.c:905)
    lamda()
  File "/nix/store/fgcf8i2dq5jn5bm0abpsxjccmbzdcak2-python3.5-cytoolz-0.7.4/lib/python3.5/site-packages/cytoolz/tests/test_docstrings.py", line 85, in <lambda>
    raises(KeyError, lambda: cytoolz.get_in(['y'], {}, no_default=True))
  File "cytoolz/dicttoolz.pyx", line 471, in cytoolz.dicttoolz.get_in (cytoolz/dicttoolz.c:6126)
    cpdef object get_in(object keys, object coll, object default=None, object no_default=False):
  File "cytoolz/dicttoolz.pyx", line 510, in cytoolz.dicttoolz.get_in (cytoolz/dicttoolz.c:5923)
    raise item
SystemError: <class 'KeyError'> returned a result with an error set

======================================================================
ERROR: test_itertoolz.test_get
----------------------------------------------------------------------
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/nk6l3r684z1fh6pzrbm6xrzkcz9knj57-python3.5-nose-1.3.7/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/nix/store/fgcf8i2dq5jn5bm0abpsxjccmbzdcak2-python3.5-cytoolz-0.7.4/lib/python3.5/site-packages/cytoolz/tests/test_itertoolz.py", line 179, in test_get
    assert raises(IndexError, lambda: get(10, 'ABC'))
  File "cytoolz/utils.pyx", line 13, in cytoolz.utils.raises (cytoolz/utils.c:905)
    lamda()
  File "/nix/store/fgcf8i2dq5jn5bm0abpsxjccmbzdcak2-python3.5-cytoolz-0.7.4/lib/python3.5/site-packages/cytoolz/tests/test_itertoolz.py", line 179, in <lambda>
    assert raises(IndexError, lambda: get(10, 'ABC'))
  File "cytoolz/itertoolz.pyx", line 613, in cytoolz.itertoolz.get (cytoolz/itertoolz.c:10271)
    cpdef object get(object ind, object seq, object default=no_default):
  File "cytoolz/itertoolz.pyx", line 680, in cytoolz.itertoolz.get (cytoolz/itertoolz.c:10069)
    raise val
SystemError: <class 'IndexError'> returned a result with an error set

======================================================================
ERROR: test_none_safe.test_dicttoolz
----------------------------------------------------------------------
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/nk6l3r684z1fh6pzrbm6xrzkcz9knj57-python3.5-nose-1.3.7/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/nix/store/fgcf8i2dq5jn5bm0abpsxjccmbzdcak2-python3.5-cytoolz-0.7.4/lib/python3.5/site-packages/cytoolz/tests/test_none_safe.py", line 55, in test_dicttoolz
    assert raises(TypeError, lambda: get_in([0, 1], None, no_default=True))
  File "cytoolz/utils.pyx", line 13, in cytoolz.utils.raises (cytoolz/utils.c:905)
    lamda()
  File "/nix/store/fgcf8i2dq5jn5bm0abpsxjccmbzdcak2-python3.5-cytoolz-0.7.4/lib/python3.5/site-packages/cytoolz/tests/test_none_safe.py", line 55, in <lambda>
    assert raises(TypeError, lambda: get_in([0, 1], None, no_default=True))
  File "cytoolz/dicttoolz.pyx", line 471, in cytoolz.dicttoolz.get_in (cytoolz/dicttoolz.c:6126)
    cpdef object get_in(object keys, object coll, object default=None, object no_default=False):
  File "cytoolz/dicttoolz.pyx", line 510, in cytoolz.dicttoolz.get_in (cytoolz/dicttoolz.c:5923)
    raise item
SystemError: <class 'TypeError'> returned a result with an error set

======================================================================
ERROR: test_none_safe.test_itertoolz
----------------------------------------------------------------------
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/nk6l3r684z1fh6pzrbm6xrzkcz9knj57-python3.5-nose-1.3.7/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/nix/store/fgcf8i2dq5jn5bm0abpsxjccmbzdcak2-python3.5-cytoolz-0.7.4/lib/python3.5/site-packages/cytoolz/tests/test_none_safe.py", line 183, in test_itertoolz
    assert raises(TypeError, lambda: get(1, None))
  File "cytoolz/utils.pyx", line 13, in cytoolz.utils.raises (cytoolz/utils.c:905)
    lamda()
  File "/nix/store/fgcf8i2dq5jn5bm0abpsxjccmbzdcak2-python3.5-cytoolz-0.7.4/lib/python3.5/site-packages/cytoolz/tests/test_none_safe.py", line 183, in <lambda>
    assert raises(TypeError, lambda: get(1, None))
  File "cytoolz/itertoolz.pyx", line 613, in cytoolz.itertoolz.get (cytoolz/itertoolz.c:10271)
    cpdef object get(object ind, object seq, object default=no_default):
  File "cytoolz/itertoolz.pyx", line 680, in cytoolz.itertoolz.get (cytoolz/itertoolz.c:10069)
    raise val
SystemError: <class 'TypeError'> returned a result with an error set

----------------------------------------------------------------------
Ran 145 tests in 0.139s

FAILED (errors=4)
```

**Comment by eriknw** [comment]
On it.  I'll push a release with a fix today too.  Thanks.
